[package]
name = "rusty-minesweeper"
authors = ["Arthur Welf"]
version = "0.1.0"
edition = "2021"
rust-version = "1.79.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.92"
